### ISSUE TITLE
Snippets in folder 'javascript' ignored when JavaScript package is ignored

### ISSUE THREAD

**Issue by IvoVermeer** [NicoSantangelo/sublime-jasmine#14]
Hi,

Great work on the snippets, I use them all the time. However, I recently installed [Babel](https://packagecontrol.io/packages/Babel) and I disabled the default JavaScript package. I'm not sure if I'm going to stick with that setup, but ignoring the package will cause ST3 to somehow also ignore the folder `javascript` in the `snippets` folder in your package. When I rename that folder to something else like `default`, the snippets show up again in autocompletion.

**Comment by NicoSantangelo** [comment]
Huh thats unexpected, thanks so much for the report

I think I'll remove the `javascript` folder and move the snippets on  to the root path to avoid this. I'll try to get a release later today.

**Comment by IvoVermeer** [comment]
Hi Nico,

That's quick! I just tried and it works now. Thanks for fixing!
