### ISSUE TITLE
Add `ddescribe` and `iit` to syntax highlighter.

### ISSUE THREAD

**Issue by fiznool** [NicoSantangelo/sublime-jasmine#3]
These are used in some patches of Jasmine to run only that particular suite or spec, e.g. the version of Jasmine that ships with Karma.

**Comment by NicoSantangelo** [comment]
This is a nice addition! 

The problem is that to my knowledge its not on Jasmine Core (I might be wrong) so I think it would create some confusion.
I think I could add `fdescribe` and `fit` which seems to be the [Jasmine alternative](http://jasmine.github.io/2.1/focused_specs.html)

**Comment by fiznool** [comment]
Oh, great. I didn't even know `fdescribe` or `fit` existed until just now. That would be a very useful addition.

**Comment by NicoSantangelo** [comment]
Let me know how it goes, the snippets, the last release, 3.2.0, contains the snippets (it may take a bit to SublimeText to update if you're using PackageControl)

**Comment by fiznool** [comment]
Looks great. Can you also add the `fdescribe` and `fit` to the syntax highlighter?

**Comment by NicoSantangelo** [comment]
@fiznool Oh! I completely forgot about that, will do
