### ISSUE TITLE
snippet are shown twice

### ISSUE THREAD

**Issue by orizens** [NicoSantangelo/sublime-jasmine#5]
hi.  
thanks for this plugin - I use it a lot.  
with latest version, i can see snippets twice in the auto-complete:  
![screen shot 2015-03-10 at 4 01 03 pm](https://cloud.githubusercontent.com/assets/878660/6576284/b96e3cf0-c73e-11e4-94d1-cf194457fd32.png)

**Comment by NicoSantangelo** [comment]
Hello!

When did you start seeing the repeated snippets? Did you use the ` Toggle quotes`  command?
Restarting Sublime fixes it?

Thanks for the heads up!

**Comment by orizens** [comment]
hi.
i started seeing it about a week ago.
I didn't use the toggle quotes command.
restart doesn't fix it.

I'm on mac os 10.10.2.

**Comment by NicoSantangelo** [comment]
Ok, thanks for the info, I'll take a look today and let you know!

**Comment by NicoSantangelo** [comment]
Unfortunately I can't seem to reproduce the issue with a fresh install of the package.

Are you using Package Control? I suspect it might be a problem with the update. I hate to ask, but re-installing works?

**Comment by NicoSantangelo** [comment]
I'm closing this for now!
But if you have any news about it, please let me know!
