### ISSUE TITLE
Jasmine syntax breaks autocompletions

### ISSUE THREAD

**Issue by durz** [NicoSantangelo/sublime-jasmine#6]
When Jasmine is used as the active syntax autocompletion always shows "No available completion" but when regular JavaScript is used as the syntax, autocompletions work as expected.

![jasmine-snippets](https://cloud.githubusercontent.com/assets/4900094/7363441/a6e476a8-edbd-11e4-8f35-21f35c3feff1.png)

Sublime text version 3083 and sublime-jasmine installed through package control.

This happens regardless of what scope you are currently in. To get around this, I'm just using the snippets while in the JavaScript syntax.

**Comment by NicoSantangelo** [comment]
Which autocomplete are you using?

The problem seems to be the file Syntax (changing from Javascript to Jasmine)

**Comment by durz** [comment]
I'm not using any special autocomplete, just the default Sublime Text one (Ctrl+Space). And yes, this only happens in the Jasmine syntax.

**Comment by NicoSantangelo** [comment]
Allright!
I don't remember if I can tell Sublime which autocomplete to use or if I have to add a custom one for Jasmine, but I'll take a look as soon as I can.

**Comment by NicoSantangelo** [comment]
Hello @durz, sorry for the massive delay.

I can't seem to reproduce the error, I've recorded a small gif to see if I understood correctly:
![test](https://cloud.githubusercontent.com/assets/692077/7781554/5055db58-00c6-11e5-9663-8511233447f1.gif)

Are you still having this error? Do you have by any chance another jasmine package?

Sorry again!

**Comment by durz** [comment]
Hey mate, those are the correct steps, though I found out that this was caused by the angularjs-suiblime-package. I first thought it was because of this jasmine package since it was only happening in the Jasmine syntax, but it now seems like the angular package and this don't work together.

**Comment by NicoSantangelo** [comment]
Thanks a lot for letting me know!

**Comment by alexilyaev** [comment]
@durz You're right, removing AngularJS package fixes it, but what if you need them both?
Have you opened and issue on their Issues page?
