### ISSUE TITLE
Mismatch between the docs and some actual snippets

### ISSUE THREAD

**Issue by alexilyaev** [NicoSantangelo/sublime-jasmine#7]
Looking at `Jasmine JS > snippets > single-quotes > spyOn.and.returnValue.sublime-snippet`.

The snippet itself is for `spyOn.and.callFake`, which btw is not in the docs.

Also, `spyOn.and.throwError.sublime-snippet` has `spyOn.and.callFake` as well.

I think there are other mismatches.
Can we get it fixed?

**Comment by NicoSantangelo** [comment]
This is up!
Let me know if anything comes up.
