### ISSUE TITLE
Snippet trigger for `spyOn` is too short

### ISSUE THREAD

**Issue by alexilyaev** [NicoSantangelo/sublime-jasmine#8]
The trigger for `spyOn` is `s`, pressing `s` in the code editor pops up too many options.

I think the trigger should have another letter to distinguish it.

**Comment by NicoSantangelo** [comment]
Hum I agree. 

Do you have any suggestions for the new trigger?

**Comment by NicoSantangelo** [comment]
While we're at it, `jasmine.any` ( a⇥ ) it's a bit short too

**Comment by alexilyaev** [comment]
`so` or just `spy` :-)

**Comment by NicoSantangelo** [comment]
This is up!
Let me know if anything comes up.
