### ISSUE TITLE
Add `toThrowError`

### ISSUE THREAD

**Issue by alexilyaev** [NicoSantangelo/sublime-jasmine#9]
There's a `toThrowError` method which checks the thrown type and message in one go.

See 2.1 spec:
http://jasmine.github.io/2.1/introduction.html

**Comment by NicoSantangelo** [comment]
Will do!

What do you think about using `tte` as trigger?

**Comment by alexilyaev** [comment]
`tte` is great

**Comment by NicoSantangelo** [comment]
This is up!
Let me know if anything comes up.
